name: GraphicJungle
favicon: null
layout_spectrum: 0.9045074426103383
typography_spectrum: 0.056737670209258795
title: the GraphicJungle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#626262'
    - '#bababa'
    - '#4b9408'
  brandStrength: 0.13001436460763216
  lightness: 0.0036575307603925467
  saturation: 0.7884869582485408
  rhythmicContrast: 0.34346951893530786
purpose: []
